# Generated by Django 4.0.6 on 2022-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
